#pragma once

// NOLINTBEGIN
#define SPARK_VERSION_MAJOR "1"

#define SPARK_VERSION_MINOR "0"

#define SPARK_VERSION_PATCH "0"

#define SPARK_VERSION SPARK_VERSION_MAJOR "." SPARK_VERSION_MINOR "." SPARK_VERSION_PATCH

// NOLINTEND
